version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/source/lambda/shared"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/cdk"
    schedule:
      interval: "weekly"
